---
title: "Campaign Memo"
format:
    html: default
    pdf: 
      documentclass: article
      fontsize: 12pt
      colorlinks: true
      citecolor: DarkOrchid
      linkcolor: DarkOrchid
      urlcolor: DarkOrchid
      geometry: margin=1in
      subtitle: | 
        | POL 310 - Religion and Politics in the U.S. \vspace{1em}
        | Professor Enrique Quezada-Llanes \vspace{-3em}
---

:::{.callout-important}
## Deadlines

1. Full draft for peer review due November 11 at 2:30 pm on Canvas. You **must** turn in a full draft on Canvas by class time so that one of your peers can give you feedback. In turn, you will give feedback to a classmate during that class period.

2. Final Draft Due November 22 at 11:59 pm on Canvas.
:::


## Purpose

This assignment will help you think critically about the role of religious voters in American elections, analyzing the various religious and non-religious groups that make up the U.S. electorate. In addition, it will help you communicate these ideas in the context of a campaign.

## Task

*Write a 4- to 6-page memo for a Senate campaign (single-spaced, 12-point font, 1-inch margins). First, choose a Senate race and define your candidate (provide information on the candidate as an appendix). Next, imagine you are part of the staff and have been hired specifically to help the campaign define its strategy for religious outreach. In the memo, provide your candidate and the campaign with the information and advice they need to understand the religious landscape of their state and how this might impact any campaign messaging and/or mobilization efforts.*

Make sure to provide clear takeaways for your candidate and campaign. Think about three things you want the staff to remember and be able to execute. The information and analysis you present support those conclusions.


## Criteria for success

A successful essay will:

1. Describe the religious and political characteristics of the constituency.
2. Provide an analysis of the potential for mobilizing these voters and how you would do this.
3. Clearly define three takeaways for the campaign about how to reach out to religious voters considering the proportion of non-religious voters in the district.
4. Have a coherent structure (paragraphs and headers are your friends here) and no grammatical errors.^[I recommend you use software like Grammarly to have one less thing to worry about.]
5. Reference at least two readings from class using [Chicago style](https://politics.ucsc.edu/undergraduate/chicago%20style%20guide.pdf) for citations (i.e., footnotes). 

Cite academic work in an appropriate tone for the audience. For example, I recommend not using the article's title or even mentioning the authors in the text. Instead, just say "researchers," "scholars," "political scientists," "sociologists," or use any other general terms. The full reference should be in the footnote, per Chicago style. 


## Resources

You can find examples, data sources, and guidelines for peer review [here](../resource/campaign-memo-resources.qmd).


