---
title: "Week 7: Mobilization and Vote Choice"
---

::: {.content-visible when-format="pdf"}

## Week 7 - Mobilization and Vote Choice

:::


[//]: <> (Need to write intro)

### Monday, October 7

- Wald, Kenneth D., and David C. Leege. 2010. "Mobilizing religious differences in American politics." In *Religion and Democracy in the United States: Danger or Opportunity?* Alan Wolfe and Ira Katznelson (eds). Princeton, NJ: Princeton University Press. (Chapter 11: pp. 355-381.) {{< fa file-pdf >}} available on Canvas.



### Wednesday, October 9

- Kalkan, Kerem Ozan, Geoffrey C. Layman, and John C. Green. 2018. "Will Americans Vote for Muslims? Cultural Outgroup Antipathy, Candidate Religion, and U.S. Voting Behavior." *Politics and Religion* 11(4): 798–829. [{{< fa university >}}](https://search.ebscohost.com/login.aspx?direct=true&AuthType=shib&db=poh&AN=132890314&site=eds-live&scope=site&custid=asc1) {{< fa pen >}}



:::{.callout-important}

### Deadline

Front end of congregational visit paper due Friday, October 11 (updated), at 11:59pm on Canvas

:::


 
::: {.content-visible when-format="html"}

---
 
### Further Reading

- Putnam, Robert and David Campbell. 2010. "Religion in American Politics." *American Grace.* New York: Simon & Schuster. (Chapter 11: pp. 369-418.) {{< fa file-pdf >}} available on Canvas.

- Coe, Kevin, and David Domke. 2006. "Petitioners or Prophets? Presidential Discourse, God, and the Ascendancy of Religious Conservatives." *Journal of Communication* 56: 309–330. {{< fa file-pdf >}} available on Canvas.

- Albertson, Bethany L. 2015. "Dog-Whistle Politics: Multivocal Communication and Religious Appeals." *Political Behavior* 37(1): 3–26.


:::

