---
title: "Final Guide"
---


This is a list of concepts and frameworks with which you should be familiar for the final exam. You might be asked to define and/or apply any of these during the examination. You might not be directly asked about these terms, but they can help you answer some of the questions.

Make sure to also review the midterm exam as some of those questions will reappear in the final.


1.  Religion in the First Amendment
2.  Davis' (2001) framework of separation, integration, and accommodation
3. The evolution of religious divisions ("conflict") in the twentieth century (Putnam and Campbell 2010, Layman 2001)
4. Culture wars model
    - Is there a culture war?
    - The role of elites in mobilizing religious differences
5. Black Protestants and the Black Church
    - Why do we talk about there being a Black Church? (think theological orientations, history, leadership)
6.Latino Catholics and Latino Protestants
    - Why is there no Latino Church? Or is there one? (think theological orientations, history, leadership)
7. Religious minorities (which groups are considered religious minorities?)
    - Religious and political orientations of religious minorities
    - Mobilization of religious minorities
8. The Nones
    - Who are the nones?
    - The religious and political orientations of the nones
9. Evangelicals
    - Who are they and how do we identify them
    - Key historical events for the role of evangelicals in society
    - Evangelical toolbox (Emerson and Smith 2000)
10. White Church
    - Explanations for how race has shaped (white) American Christianity
    - Racial attitudes among white Christians (Jones 2020)
11. Religious Left
    - Examples of the Religious Left
    - Potential for mobilization (think elite level, mass level, religious orientations)
12. How politics shapes religion
    - Impact on religious behavior
    - Impact on religious identities


