---
title: Resources for Campaign Memo
---

## Examples of Campaign Memos

Here are some examples of campaign and political memos. These address various groups a campaign might target so it will be useful to look at them again. Use these examples to understand the genre and see how they are structured. Consider the following: What is important in these pieces of writing? How are those goals reflected in how the text is organized? How is it reflected in the tone of the piece?

- [Biden campaign memo example](https://www.wispolitics.com/2020/biden-campaign-memo)
- [Buttigieg campaign memo example](https://www.documentcloud.org/documents/6785938-Path-to-Nomination.html)
- [Memo to Trump on fake electors scheme](https://int.nyt.com/data/documenttools/chesebro-dec-6-memo/ce55d6abd79c2c71/full.pdf)
- [DeSantis memo](https://s3.documentcloud.org/documents/23874013/0051_001.pdf)


## Data Sources

The following websites have some helpful data:

- [PRRI's American Values Atlas](https://ava.prri.org/)
- [PRRI's AVA State Profiles](https://ava.prri.org/state?state=GA)
- [PRRI - Some County-level Maps (may be useful)](https://www.prri.org/research/2020-census-of-american-religion/#page-section-1)
- [2020 U.S. Religious Census - Group detail data by nation, state, county and metro](https://www.usreligioncensus.org/sites/default/files/2023-06/2020_USRC_Group_Detail.xlsx)
- [2014 Pew Data on Percentage of Religious Tradition by State](https://www.pewresearch.org/religion/religious-landscape-study/compare/religious-tradition/by/state/)


## Guide for Peer Review

Just like we did before, you will provide feedback on this assignment for one of your peers. This time, we will do this through Canvas. After the deadline to submit your draft, Canvas will automatically assign you someone else's draft.

As you may have heard me say in class before, and for lack of a better phrase, I want you to be ***constructively ruthless*** AND ***nice***.^[There is no either-or here, it is both-and (as some religious traditions like to say).] Point out what is well done and areas for improvement (organization, formatting, missing information, unsupported conclusions, etc.). You can use the following questions as a guide to evaluate the draft:

1. Does the memo provide clear takeaways on the first page?
2. Is the purpose of the memo clear?
3. Does the memo describe the *religious* characteristics of the state as a whole?
4. Does the memo describe the *political* characteristics of the state as a whole?
5. Given the religious characteristics of the state population, does the memo discuss particular religious groups in more detail (i.e., their religious and political orientations)?
6. Given the characteristics of the candidate *and* of the state population, does the memo provide a clear answer to whether and how the candidate should reach out to potential voters?
7. Does the memo provide clear, actionable strategies for the campaign staff?
8. Does the memo use data and appropriately cite sources (e.g., using footnotes)?
9. Does the memo provide sufficient information without overwhelming the reader?
10. Does the memo's organization help effectively communicate the main points?
11. Does the memo use headers in a clear way? Are the paragraphs single spaced? Is there space between paragraphs? Does the memo use lists and bullet points appropriately?

